### ISSUE TITLE
All the methods tested in the paper all limited in R language?

### ISSUE THREAD

**Issue by YubinXie** [LuyiTian/sc_mixology#11]
I noticed that most scripts here are R scripts. Does this mean all the methods benchmarked in the paper are limited on the R language? As we know that there are also many Python-only methods for scRNA seq data. Thanks!

**Comment by LuyiTian** [comment]
Yes the scope of the study is mostly limited to R. The Scanorama is a python package and called in R using reticulate package. For the data we have provided the csv version as requested (https://github.com/LuyiTian/CellBench_data/issues/9).
