### ISSUE TITLE
How to perform log transformation？

### ISSUE THREAD

**Issue by lovivi** [LuyiTian/sc_mixology#13]
I can't repeat the log transformation of count in the data, may i ignore something step?
> max(log2(c(sce_sc_CELseq2_qc@assays$data@listData$counts)+1))
[1] 11.53819
> max(log2(c(sce_sc_CELseq2_qc@assays$data@listData$counts)))
[1] 11.5377
> max(c(sce_sc_CELseq2_qc@assays$data@listData$logcounts))
[1] 11.84594

**Comment by LuyiTian** [comment]
The data in logcounts data slot are log normalized expression using scran package, not just log2 transformed count value. 
The code I used looks like:
```
sce <- computeSumFactors(sce)
sce <- normalize(sce)
```

The scran webpage have more detail: bioconductor.org/packages/release/bioc/vignettes/scran/inst/doc/scran.html

**Comment by lovivi** [comment]
Sorry, I still can't get the result of *logcounts*. What parameters did I miss? Or I have a suspicious warning when I run it.
> load('./bulk_sc/CellBench_script/data/sincell_with_class.RData')
> max(c(sce_sc_CELseq2_qc@assays$data@listData$logcounts))       ## 11.84594
[1] 11.84594
> max(log2(c(sce_sc_CELseq2_qc@assays$data@listData$counts)+1))
[1] 11.53819
> max(log2(c(sce_sc_CELseq2_qc@assays$data@listData$counts)))
[1] 11.5377
> #######################
> sce <- sce_sc_CELseq2_qc
> logcounts(sce) <- NULL
> #counts(sce) <- counts(sce)+1
> sce <- scran::computeSumFactors(sce)
> sce <- scater::normalize(sce)
Warning message:
In .get_all_sf_sets(object) :
  spike-in set 'ERCC' should have its own size factors
> max(c(sce@assays$data@listData$logcounts))                   ## 11.84798
[1] 11.84798
> ########################
> sce <- sce_sc_CELseq2_qc
> logcounts(sce) <- NULL
> sce <- scran::computeSumFactors(sce)
> sce <- BiocGenerics::normalize(sce)
Warning message:
In .get_all_sf_sets(object) :
  spike-in set 'ERCC' should have its own size factors
> max(c(sce@assays$data@listData$logcounts))                   ## 11.84798
[1] 11.84798

**Comment by lovivi** [comment]
ok, i find the method!
> sce2 <- scran::computeSpikeFactors(sce, general.use=FALSE)
> sce2 <- normalize(sce2)
