### ISSUE TITLE
Question regarding 10x UMIs

### ISSUE THREAD

**Issue by lvlahos343** [LuyiTian/sc_mixology#15]
I've been trying to access the UMI matrix for the 'sce_sc_10x_qc' dataset. However, the documentation seems to only show how to retrieve a count matrix, one that is clearly not de-duplicated given the extremely high number of reads for each cell. 

Is the UMI matrix for the 10x data supplied anywhere within the package? And if not, where are the fastqs and/or BAM files we'd need in order to generate a de-duplicated UMI matrix?

**Comment by LuyiTian** [comment]
Sorry for confusion. We only provide UMI count matrix. The cell line we used is transcriptional active so there are a lot of mRNA in each cells. I will update the documents.
