### ISSUE TITLE
Is the 10X data 3' or 5'? Which chemistry was used?

### ISSUE THREAD

**Issue by Puriney** [LuyiTian/sc_mixology#18]
> ... where one part was then processed by the Chromium 10× single cell platform using the manufacturer’s (10x Genomics) protocol.

But for 10X dataset, I was wondering are they 3' or 5' scRNA-seq? Which chemistry? V2 / V3?

Thank you.

**Comment by LuyiTian** [comment]
they are 3' scRNAseq with v2 chemistry.
