### ISSUE TITLE
Plans to make into ExperimentHub package?

### ISSUE THREAD

**Issue by sa-lee** [LuyiTian/sc_mixology#2]
https://www.bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html

This seems like a great way of both 
a. making your data easily accessible to other Bioconductor users
b. easily integrate this data into any workflows you or the team plan to write in the future

**Comment by robertamezquita** [comment]
+1, I want to re-up this issue as I think this would be a highly useful way for the broader community to use/access this data. It would only require relatively modest refactoring of the current code to be in a package format, and would conversely have an outsize effect on its visibility.

**Comment by robertamezquita** [comment]
Hi, just wanted to follow-up here on this issue - I would like to feature CellBench_data in some workflows that I plan to publish, and it would be great to be able to access the data programmatically through an ExperimentHub based package similar to TENxPBMCData or TENxBrainData. Are there any updates on your end regarding this (either affirmative or negative?)

**Comment by LuyiTian** [comment]
glad to hear the data is useful. I do have the plan to make an ExperimentHub package but not recently. The current dataset won't move or change so you can safely use the link. We are busy doing the experiment to add more data, using recent protocols such as ATAC-seq and cell hashing.
