### ISSUE TITLE
Number of cells discrepancy

### ISSUE THREAD

**Issue by sgmccalla** [LuyiTian/sc_mixology#20]
I have a question about the data available on ncbi and the cell cluster labels. I downloaded [GEO data](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE118767), but am noticing that there are fewer cells in the ground truth true label files on github than in the GEO single cell dataset. Is there a cell cluster file available that contains more cells?

For example, there are 4001 cells for sc_10x [GSM3022245](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3022245), but only 902 cells in the ground truth true label dataset; there are 384 cells for sc_CEL-seq2 [GSM3336845](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3336845), but 274 cells in the ground truth  true label dataset; there are 4001 sc_Drop-seq [GSM3336849](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3336849), but 225 cells in the ground truth  true label dataset.

**Comment by LuyiTian** [comment]
for the 10x, I think you might refer to the wrong reference. We had two batch of 10x data. The first batch have around 900 cells (3 cell lines), second have around 4000 cells(5 cell lines). For sc_CEL-seq2 5 cell line mixtures (3X384 well plate), there are more doublets than we would expect so we exclude this data when we compare some methods, such as clustering. The Drop-seq data contains around 200 cells. 
The gene count matrixs were acquired by scPipe, which contains top X cells ranked by reads and it does not perform QC in preprocessing step. So the cell number in gene count matrix does not reflact the real cell number, just result of the parameter.
