### ISSUE TITLE
known cell grouping variable

### ISSUE THREAD

**Issue by AlemuTA** [LuyiTian/sc_mixology#6]
Dear Luyi Tian,

First, I'm impressed by the great work, and good luck for your publication procedure. 

I want to use the three single cell RNA-seq datasets (sc_CEL-seq2, sc_10x, and sc_Drop-seq) to evaluate differential expression (DE) analysis tools, such as MAST, scDD, edgeR, etc. Such tools for DE analysis require the cell grouping variable (aka conditions, treatment, group...) apriori.  The purpose of DE analysis it to identify the set of genes that show statistically significant differential expressions across the known **conditions** of interest. 

However, after successfully downloading the datasets and their respective cell annotation file, I couldn't find any cell grouping variable (for example the cell line group, sorry if I'm wrong) to be able to apply DE analysis. Perhaps, I have to do this after cell clustering analysis. Right? Therefore, my questions are, is there any known cell grouping variable? or is it possible to know which cell comes from which cell population in the datasets?

Best regards,
Alemu
(Department of Data Analysis and Mathematical Modeling, Ghent University, Belgium)

**Comment by LuyiTian** [comment]
the annotation and relevant metadata is stored in `colData(SCE_object_you_downloaded)`. let me know if you have any questions. 

You can get the DE genes from bulk sample either from our previous study: "RNA-seq mixology: Designing realistic control experiments to compare protocols and analysis methods" (bulk but not the same batch of cells, grown at different time), or from the 90 cell control dataset (the same cells but not really bulk). And these DE genes can be used as ground truth for comparison.

**Comment by AlemuTA** [comment]
Thanks for the quick response. I downloaded the data from the GEO database, and I did not find a _SingleCellExperment_ object to extract those meta data. I think I need to download the data again from this GitHub repository. Thanks again.
