### ISSUE TITLE
Fix encoding(?) of the *_call.R scripts in script/clustering/Clustering_Algorithms

### ISSUE THREAD

**Issue by lianos** [LuyiTian/sc_mixology#7]
Thank you for organizing the analyses from your paper into such a useful repository.

It seems like something strange happened to the `*_call.R` files in the `script/clustering/Clustering_Algorithms` directory?

They can't be viewed via the code browser online, and pulling down this repo locally, it seems like these files are somehow binary encoded or some such ... or?

**Comment by LuyiTian** [comment]
sorry I didn't correctly copy them from our server. the error has been corrected.
