### ISSUE TITLE
Rdata file contains variables with unclear names

### ISSUE THREAD

**Issue by cgreene** [LuyiTian/sc_mixology#8]
Based on the README and variable names, I'm gathering that sce10x_qc has the 10X counts after QC. There are two other variables as well, `sce4_qc` and `scedrop_qc_qc`. I'm guessing the dropseq is `scedrop_qc_qc` (any reason for the double _qc?). Does that mean that the CEL-seq2 is the `sce4_qc` variable?

**Comment by LuyiTian** [comment]
yes, sce4_qc contains the CEL-seq2 single-cell data. 
the reason for double qc is that Drop-seq contains empty droplets with ambient RNA so we remove these background barcode again after initial QC. 
We are clean up the data and script right now, sorry for the confusion. 
There will be more single-cell data, with more cell lines and other protocols as well.
