### ISSUE TITLE
Loading the data from Python

### ISSUE THREAD

**Issue by dganguli** [LuyiTian/sc_mixology#9]
This is a great benchmarking resource! Are there any plans to make the data inter-operable with the Python eco-system?  Ideally, instead of loading R objects, it would be nice to also be able to load loom files or csv files for each dataset. 

I have tried using Seurat's conversion tool (https://satijalab.org/seurat/conversion_vignette.html) for SingleCellExperiment -> loom but have not been able to get that to work.

**Comment by LuyiTian** [comment]
Have put that in my TODO list. we are clean up the scripts and adding more data.

**Comment by LuyiTian** [comment]
CSV files of count data and metadata have been updated: https://github.com/LuyiTian/CellBench_data/commit/19667e111aac52abbfcaa6fff07da2fd05984709
